server:
  port: 80
  servlet:
    register-default-servlet: true
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:15432/postgres
    #url: ENC(taCIdHdTyfP0DRdf2RfbUJlewo3Zisn2LciGah93eH8+NPVdKLXcdlzWSaveFWIu4VKBEFgeByw=)
    username: postgres
    #username: ENC(sp5KoEZ0iyH21GfJ3IVppw==)
    password: postgres
    #password: ENC(p5+M4mWQi1lt/kSZH/xa1A==)
    hikari:
      maximum-pool-size: 5
      minimum-idle: 3
      #connection-timeout: 30000
      #idle-timeout: 600000
      #validation-timeout: 40000

  jpa:
    properties:
      hibernate:
        hbm2ddl.auto: validate
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

#jasypt:
#  encryptor:
#    bean: jasyptStringEncryptor

#  jackson:
#    default-property-inclusion: non_empty
#    serialization:
#      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: info
    org.hibernate.type.descriptor.sql: trace
    #org.springframework.web: info
    #org.hibernate.SQL: debug
    #file:
    #path: target/logs

#jwt:
#  header: Authorization
#  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
#  token-validity-in-seconds: 86400